/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AccountSubType.h
 *
 * 
 */

#ifndef DEV_HAVEN_CLIENT_MODEL_AccountSubType_H_
#define DEV_HAVEN_CLIENT_MODEL_AccountSubType_H_


#include "../ModelBase.h"


namespace dev {
namespace haven {
namespace client {
namespace model {

class  AccountSubType
    : public ModelBase
{
public:
    AccountSubType();
    virtual ~AccountSubType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eAccountSubType 
    {
        AccountSubType_AUTO,
        AccountSubType_BROKERAGE,
        AccountSubType_CASH_ISA,
        AccountSubType_CASH_MANAGEMENT,
        AccountSubType_CD,
        AccountSubType_CHECKING,
        AccountSubType_COMMERCIAL,
        AccountSubType_CONSTRUCTION,
        AccountSubType_CONSUMER,
        AccountSubType_CREDIT,
        AccountSubType_CREDIT_CARD,
        AccountSubType_DEPOSITORY,
        AccountSubType_EDUCATION_SAVINGS_ACCOUNT,
        AccountSubType_GIC,
        AccountSubType_HEALTH_REIMBURSEMENT_ARRANGEMENT,
        AccountSubType_HOME,
        AccountSubType_HOME_EQUITY,
        AccountSubType_HSA,
        AccountSubType_IRA,
        AccountSubType_ISA,
        AccountSubType_KEOGH,
        AccountSubType_LIF,
        AccountSubType_LINE_OF_CREDIT,
        AccountSubType_LIRA,
        AccountSubType_LOAN,
        AccountSubType_LRIF,
        AccountSubType_LRSP,
        AccountSubType_MONEY_MARKET,
        AccountSubType_MORTGAGE,
        AccountSubType_MUTUAL_FUND,
        AccountSubType_NON_TAXABLE_BROKERAGE_ACCOUNT,
        AccountSubType_OTHER,
        AccountSubType_OVERDRAFT,
        AccountSubType_PAYPAL,
        AccountSubType_PENSION,
        AccountSubType_PREPAID,
        AccountSubType_PRIF,
        AccountSubType_PROFIT_SHARING_PLAN,
        AccountSubType_RDSP,
        AccountSubType_RECURRING,
        AccountSubType_RESP,
        AccountSubType_RETIREMENT,
        AccountSubType_REWARDS,
        AccountSubType_RLIF,
        AccountSubType_ROTH,
        AccountSubType_ROTH_401K,
        AccountSubType_RRIF,
        AccountSubType_RRSP,
        AccountSubType_SAFE_DEPOSIT,
        AccountSubType_SARSEP,
        AccountSubType_SAVINGS,
        AccountSubType_SEP_IRA,
        AccountSubType_SIMPLE_IRA,
        AccountSubType_SIPP,
        AccountSubType_STOCK_PLAN,
        AccountSubType_STUDENT,
        AccountSubType_TFSA,
        AccountSubType_THRIFT_SAVINGS_PLAN,
        AccountSubType_T_401A,
        AccountSubType_T_401K,
        AccountSubType_T_403B,
        AccountSubType_T_457B,
        AccountSubType_T_529,
        AccountSubType_UGMA,
        AccountSubType_UTMA,
        AccountSubType_VARIABLE_ANNUITY,
    };

    eAccountSubType getValue() const;
    void setValue(eAccountSubType const value);

    protected:
        eAccountSubType m_value;
};

}
}
}
}

#endif /* DEV_HAVEN_CLIENT_MODEL_AccountSubType_H_ */
