/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "AddAnnotationResponse.h"

namespace dev {
namespace haven {
namespace client {
namespace model {




AddAnnotationResponse::AddAnnotationResponse()
{
}

AddAnnotationResponse::~AddAnnotationResponse()
{
}

void AddAnnotationResponse::validate()
{
    // TODO: implement validation
}

web::json::value AddAnnotationResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Transactions )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val[utility::conversions::to_string_t("transactions")] = web::json::value::array(jsonArray);
    }

    return val;
}

void AddAnnotationResponse::fromJson(const web::json::value& val)
{
    {
        m_Transactions.clear();
        std::vector<web::json::value> jsonArray;
        for( auto& item : val.at(utility::conversions::to_string_t("transactions")).as_array() )
        {
            if(item.is_null())
            {
                m_Transactions.push_back( std::shared_ptr<CleanTransaction>(nullptr) );
            }
            else
            {
                std::shared_ptr<CleanTransaction> newItem(new CleanTransaction());
                newItem->fromJson(item);
                m_Transactions.push_back( newItem );
            }
        }
    }
}

void AddAnnotationResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Transactions )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("transactions"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
            }
}

void AddAnnotationResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_Transactions.clear();

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("transactions"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Transactions.push_back( std::shared_ptr<CleanTransaction>(nullptr) );
            }
            else
            {
                std::shared_ptr<CleanTransaction> newItem(new CleanTransaction());
                newItem->fromJson(item);
                m_Transactions.push_back( newItem );
            }
        }
    }
}

std::vector<std::shared_ptr<CleanTransaction>>& AddAnnotationResponse::getTransactions()
{
    return m_Transactions;
}

void AddAnnotationResponse::setTransactions(const std::vector<std::shared_ptr<CleanTransaction>>& value)
{
    m_Transactions = value;
    
}

}
}
}
}


