/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Balance.h
 *
 * 
 */

#ifndef DEV_HAVEN_CLIENT_MODEL_Balance_H_
#define DEV_HAVEN_CLIENT_MODEL_Balance_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace dev {
namespace haven {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  Balance
    : public ModelBase
{
public:
    Balance();
    virtual ~Balance();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Balance members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCurrent() const;
    
    void setCurrent(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAvailable() const;
    bool availableIsSet() const;
    void unsetAvailable();

    void setAvailable(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getLimit() const;
    bool limitIsSet() const;
    void unsetLimit();

    void setLimit(const utility::string_t& value);


protected:
    utility::string_t m_Current;
        utility::string_t m_Available;
    bool m_AvailableIsSet;
    utility::string_t m_Limit;
    bool m_LimitIsSet;
};


}
}
}
}

#endif /* DEV_HAVEN_CLIENT_MODEL_Balance_H_ */
