/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CleanCategory.h"

namespace dev {
namespace haven {
namespace client {
namespace model {



CleanCategory::CleanCategory()
{
}

CleanCategory::~CleanCategory()
{
}

void CleanCategory::validate()
{
    // TODO: implement validation
}

web::json::value CleanCategory::toJson() const
{
    web::json::value val = web::json::value::object();

    
    if (m_value == eCleanCategory::CleanCategory_Arts) val = web::json::value::string(U("Arts"));
    if (m_value == eCleanCategory::CleanCategory_Music) val = web::json::value::string(U("Music"));
    if (m_value == eCleanCategory::CleanCategory_Movies &amp; Television) val = web::json::value::string(U("Movies &amp; Television"));
    if (m_value == eCleanCategory::CleanCategory_Newspaper &amp; Magazines) val = web::json::value::string(U("Newspaper &amp; Magazines"));
    if (m_value == eCleanCategory::CleanCategory_Other Entertainment) val = web::json::value::string(U("Other Entertainment"));
    if (m_value == eCleanCategory::CleanCategory_Theater) val = web::json::value::string(U("Theater"));
    if (m_value == eCleanCategory::CleanCategory_Gambling) val = web::json::value::string(U("Gambling"));
    if (m_value == eCleanCategory::CleanCategory_Deposit) val = web::json::value::string(U("Deposit"));
    if (m_value == eCleanCategory::CleanCategory_Withdrawal) val = web::json::value::string(U("Withdrawal"));
    if (m_value == eCleanCategory::CleanCategory_Dividends) val = web::json::value::string(U("Dividends"));
    if (m_value == eCleanCategory::CleanCategory_Buy) val = web::json::value::string(U("Buy"));
    if (m_value == eCleanCategory::CleanCategory_Sell) val = web::json::value::string(U("Sell"));
    if (m_value == eCleanCategory::CleanCategory_Other Investments) val = web::json::value::string(U("Other Investments"));
    if (m_value == eCleanCategory::CleanCategory_Gas &amp; Fuel) val = web::json::value::string(U("Gas &amp; Fuel"));
    if (m_value == eCleanCategory::CleanCategory_Car Parts) val = web::json::value::string(U("Car Parts"));
    if (m_value == eCleanCategory::CleanCategory_Toll Fee) val = web::json::value::string(U("Toll Fee"));
    if (m_value == eCleanCategory::CleanCategory_Parking) val = web::json::value::string(U("Parking"));
    if (m_value == eCleanCategory::CleanCategory_Traffic Tickets) val = web::json::value::string(U("Traffic Tickets"));
    if (m_value == eCleanCategory::CleanCategory_Maintenance &amp; Repairs) val = web::json::value::string(U("Maintenance &amp; Repairs"));
    if (m_value == eCleanCategory::CleanCategory_Auto Payment) val = web::json::value::string(U("Auto Payment"));
    if (m_value == eCleanCategory::CleanCategory_Auto Insurance) val = web::json::value::string(U("Auto Insurance"));
    if (m_value == eCleanCategory::CleanCategory_Public Transportation) val = web::json::value::string(U("Public Transportation"));
    if (m_value == eCleanCategory::CleanCategory_Other Car) val = web::json::value::string(U("Other Car"));
    if (m_value == eCleanCategory::CleanCategory_Taxi) val = web::json::value::string(U("Taxi"));
    if (m_value == eCleanCategory::CleanCategory_Boat) val = web::json::value::string(U("Boat"));
    if (m_value == eCleanCategory::CleanCategory_Air Travel) val = web::json::value::string(U("Air Travel"));
    if (m_value == eCleanCategory::CleanCategory_Lodging) val = web::json::value::string(U("Lodging"));
    if (m_value == eCleanCategory::CleanCategory_Ride Share &amp; Rental) val = web::json::value::string(U("Ride Share &amp; Rental"));
    if (m_value == eCleanCategory::CleanCategory_Other Travel) val = web::json::value::string(U("Other Travel"));
    if (m_value == eCleanCategory::CleanCategory_Account Maintenance) val = web::json::value::string(U("Account Maintenance"));
    if (m_value == eCleanCategory::CleanCategory_Overdraft Fee) val = web::json::value::string(U("Overdraft Fee"));
    if (m_value == eCleanCategory::CleanCategory_Insufficient Funds Fee) val = web::json::value::string(U("Insufficient Funds Fee"));
    if (m_value == eCleanCategory::CleanCategory_ATM Fee) val = web::json::value::string(U("ATM Fee"));
    if (m_value == eCleanCategory::CleanCategory_Check Order Fee) val = web::json::value::string(U("Check Order Fee"));
    if (m_value == eCleanCategory::CleanCategory_Interest Charged Fee) val = web::json::value::string(U("Interest Charged Fee"));
    if (m_value == eCleanCategory::CleanCategory_Foreign Transaction Fee) val = web::json::value::string(U("Foreign Transaction Fee"));
    if (m_value == eCleanCategory::CleanCategory_Wire Fee) val = web::json::value::string(U("Wire Fee"));
    if (m_value == eCleanCategory::CleanCategory_Excessive Transactions Fee) val = web::json::value::string(U("Excessive Transactions Fee"));
    if (m_value == eCleanCategory::CleanCategory_Late Fee) val = web::json::value::string(U("Late Fee"));
    if (m_value == eCleanCategory::CleanCategory_Card Membership Fee) val = web::json::value::string(U("Card Membership Fee"));
    if (m_value == eCleanCategory::CleanCategory_Other Fee) val = web::json::value::string(U("Other Fee"));
    if (m_value == eCleanCategory::CleanCategory_Rent) val = web::json::value::string(U("Rent"));
    if (m_value == eCleanCategory::CleanCategory_Mortgage) val = web::json::value::string(U("Mortgage"));
    if (m_value == eCleanCategory::CleanCategory_Other Housing) val = web::json::value::string(U("Other Housing"));
    if (m_value == eCleanCategory::CleanCategory_Rent Reimbursement) val = web::json::value::string(U("Rent Reimbursement"));
    if (m_value == eCleanCategory::CleanCategory_Yard &amp; Garden) val = web::json::value::string(U("Yard &amp; Garden"));
    if (m_value == eCleanCategory::CleanCategory_Credit card payment) val = web::json::value::string(U("Credit card payment"));
    if (m_value == eCleanCategory::CleanCategory_ATM Withdrawals) val = web::json::value::string(U("ATM Withdrawals"));
    if (m_value == eCleanCategory::CleanCategory_Internal Transfer) val = web::json::value::string(U("Internal Transfer"));
    if (m_value == eCleanCategory::CleanCategory_External Transfer) val = web::json::value::string(U("External Transfer"));
    if (m_value == eCleanCategory::CleanCategory_Other Transfer) val = web::json::value::string(U("Other Transfer"));
    if (m_value == eCleanCategory::CleanCategory_Loan Payment) val = web::json::value::string(U("Loan Payment"));
    if (m_value == eCleanCategory::CleanCategory_Services) val = web::json::value::string(U("Services"));
    if (m_value == eCleanCategory::CleanCategory_Legal Services) val = web::json::value::string(U("Legal Services"));
    if (m_value == eCleanCategory::CleanCategory_Accounting Services) val = web::json::value::string(U("Accounting Services"));
    if (m_value == eCleanCategory::CleanCategory_Real Estate Services) val = web::json::value::string(U("Real Estate Services"));
    if (m_value == eCleanCategory::CleanCategory_Business Services) val = web::json::value::string(U("Business Services"));
    if (m_value == eCleanCategory::CleanCategory_Computer Services) val = web::json::value::string(U("Computer Services"));
    if (m_value == eCleanCategory::CleanCategory_Online Subscriptions) val = web::json::value::string(U("Online Subscriptions"));
    if (m_value == eCleanCategory::CleanCategory_Financial Services) val = web::json::value::string(U("Financial Services"));
    if (m_value == eCleanCategory::CleanCategory_Cleaning Services) val = web::json::value::string(U("Cleaning Services"));
    if (m_value == eCleanCategory::CleanCategory_Internet) val = web::json::value::string(U("Internet"));
    if (m_value == eCleanCategory::CleanCategory_Home Insurance) val = web::json::value::string(U("Home Insurance"));
    if (m_value == eCleanCategory::CleanCategory_Renter&#39;s Insurance) val = web::json::value::string(U("Renter&#39;s Insurance"));
    if (m_value == eCleanCategory::CleanCategory_Life Insurance) val = web::json::value::string(U("Life Insurance"));
    if (m_value == eCleanCategory::CleanCategory_Other Insurance) val = web::json::value::string(U("Other Insurance"));
    if (m_value == eCleanCategory::CleanCategory_Phone Bill) val = web::json::value::string(U("Phone Bill"));
    if (m_value == eCleanCategory::CleanCategory_Utilities) val = web::json::value::string(U("Utilities"));
    if (m_value == eCleanCategory::CleanCategory_TV) val = web::json::value::string(U("TV"));
    if (m_value == eCleanCategory::CleanCategory_Other Bills) val = web::json::value::string(U("Other Bills"));
    if (m_value == eCleanCategory::CleanCategory_Paycheck) val = web::json::value::string(U("Paycheck"));
    if (m_value == eCleanCategory::CleanCategory_Interest) val = web::json::value::string(U("Interest"));
    if (m_value == eCleanCategory::CleanCategory_Reimbursement) val = web::json::value::string(U("Reimbursement"));
    if (m_value == eCleanCategory::CleanCategory_Other Income) val = web::json::value::string(U("Other Income"));
    if (m_value == eCleanCategory::CleanCategory_Tuition) val = web::json::value::string(U("Tuition"));
    if (m_value == eCleanCategory::CleanCategory_Student Loan) val = web::json::value::string(U("Student Loan"));
    if (m_value == eCleanCategory::CleanCategory_Other Education) val = web::json::value::string(U("Other Education"));
    if (m_value == eCleanCategory::CleanCategory_Health Insurance) val = web::json::value::string(U("Health Insurance"));
    if (m_value == eCleanCategory::CleanCategory_Gym) val = web::json::value::string(U("Gym"));
    if (m_value == eCleanCategory::CleanCategory_Dentist) val = web::json::value::string(U("Dentist"));
    if (m_value == eCleanCategory::CleanCategory_Doctor) val = web::json::value::string(U("Doctor"));
    if (m_value == eCleanCategory::CleanCategory_Pharmacy) val = web::json::value::string(U("Pharmacy"));
    if (m_value == eCleanCategory::CleanCategory_Medical Labs) val = web::json::value::string(U("Medical Labs"));
    if (m_value == eCleanCategory::CleanCategory_Barber and Salon) val = web::json::value::string(U("Barber and Salon"));
    if (m_value == eCleanCategory::CleanCategory_Spa) val = web::json::value::string(U("Spa"));
    if (m_value == eCleanCategory::CleanCategory_Nail and Skin) val = web::json::value::string(U("Nail and Skin"));
    if (m_value == eCleanCategory::CleanCategory_Other Health &amp; Fitness) val = web::json::value::string(U("Other Health &amp; Fitness"));
    if (m_value == eCleanCategory::CleanCategory_Groceries) val = web::json::value::string(U("Groceries"));
    if (m_value == eCleanCategory::CleanCategory_Coffee) val = web::json::value::string(U("Coffee"));
    if (m_value == eCleanCategory::CleanCategory_Restaurants) val = web::json::value::string(U("Restaurants"));
    if (m_value == eCleanCategory::CleanCategory_Alcohol) val = web::json::value::string(U("Alcohol"));
    if (m_value == eCleanCategory::CleanCategory_Bars &amp; Clubs) val = web::json::value::string(U("Bars &amp; Clubs"));
    if (m_value == eCleanCategory::CleanCategory_Other Food &amp; Dining) val = web::json::value::string(U("Other Food &amp; Dining"));
    if (m_value == eCleanCategory::CleanCategory_Clothes &amp; Apparel) val = web::json::value::string(U("Clothes &amp; Apparel"));
    if (m_value == eCleanCategory::CleanCategory_Sporting Goods) val = web::json::value::string(U("Sporting Goods"));
    if (m_value == eCleanCategory::CleanCategory_Electronics) val = web::json::value::string(U("Electronics"));
    if (m_value == eCleanCategory::CleanCategory_Games) val = web::json::value::string(U("Games"));
    if (m_value == eCleanCategory::CleanCategory_Tobacco &amp; Vaping) val = web::json::value::string(U("Tobacco &amp; Vaping"));
    if (m_value == eCleanCategory::CleanCategory_Cannabis) val = web::json::value::string(U("Cannabis"));
    if (m_value == eCleanCategory::CleanCategory_Beauty) val = web::json::value::string(U("Beauty"));
    if (m_value == eCleanCategory::CleanCategory_Books) val = web::json::value::string(U("Books"));
    if (m_value == eCleanCategory::CleanCategory_Business Equipment) val = web::json::value::string(U("Business Equipment"));
    if (m_value == eCleanCategory::CleanCategory_Home Hardware) val = web::json::value::string(U("Home Hardware"));
    if (m_value == eCleanCategory::CleanCategory_Shipping) val = web::json::value::string(U("Shipping"));
    if (m_value == eCleanCategory::CleanCategory_Software) val = web::json::value::string(U("Software"));
    if (m_value == eCleanCategory::CleanCategory_Guns &amp; Weapons) val = web::json::value::string(U("Guns &amp; Weapons"));
    if (m_value == eCleanCategory::CleanCategory_Taxes) val = web::json::value::string(U("Taxes"));
    if (m_value == eCleanCategory::CleanCategory_Government Services) val = web::json::value::string(U("Government Services"));
    if (m_value == eCleanCategory::CleanCategory_Fines) val = web::json::value::string(U("Fines"));
    if (m_value == eCleanCategory::CleanCategory_Gifts &amp; Donations) val = web::json::value::string(U("Gifts &amp; Donations"));
    if (m_value == eCleanCategory::CleanCategory_Shopping) val = web::json::value::string(U("Shopping"));
    if (m_value == eCleanCategory::CleanCategory_Other) val = web::json::value::string(U("Other"));
    if (m_value == eCleanCategory::CleanCategory_Pets) val = web::json::value::string(U("Pets"));
    if (m_value == eCleanCategory::CleanCategory_Child Care) val = web::json::value::string(U("Child Care"));

    return val;
}

void CleanCategory::fromJson(const web::json::value& val)
{
    auto s = val.as_string();

    
    if (s == utility::conversions::to_string_t("Arts")) m_value = eCleanCategory::CleanCategory_Arts;
    if (s == utility::conversions::to_string_t("Music")) m_value = eCleanCategory::CleanCategory_Music;
    if (s == utility::conversions::to_string_t("Movies &amp; Television")) m_value = eCleanCategory::CleanCategory_Movies &amp; Television;
    if (s == utility::conversions::to_string_t("Newspaper &amp; Magazines")) m_value = eCleanCategory::CleanCategory_Newspaper &amp; Magazines;
    if (s == utility::conversions::to_string_t("Other Entertainment")) m_value = eCleanCategory::CleanCategory_Other Entertainment;
    if (s == utility::conversions::to_string_t("Theater")) m_value = eCleanCategory::CleanCategory_Theater;
    if (s == utility::conversions::to_string_t("Gambling")) m_value = eCleanCategory::CleanCategory_Gambling;
    if (s == utility::conversions::to_string_t("Deposit")) m_value = eCleanCategory::CleanCategory_Deposit;
    if (s == utility::conversions::to_string_t("Withdrawal")) m_value = eCleanCategory::CleanCategory_Withdrawal;
    if (s == utility::conversions::to_string_t("Dividends")) m_value = eCleanCategory::CleanCategory_Dividends;
    if (s == utility::conversions::to_string_t("Buy")) m_value = eCleanCategory::CleanCategory_Buy;
    if (s == utility::conversions::to_string_t("Sell")) m_value = eCleanCategory::CleanCategory_Sell;
    if (s == utility::conversions::to_string_t("Other Investments")) m_value = eCleanCategory::CleanCategory_Other Investments;
    if (s == utility::conversions::to_string_t("Gas &amp; Fuel")) m_value = eCleanCategory::CleanCategory_Gas &amp; Fuel;
    if (s == utility::conversions::to_string_t("Car Parts")) m_value = eCleanCategory::CleanCategory_Car Parts;
    if (s == utility::conversions::to_string_t("Toll Fee")) m_value = eCleanCategory::CleanCategory_Toll Fee;
    if (s == utility::conversions::to_string_t("Parking")) m_value = eCleanCategory::CleanCategory_Parking;
    if (s == utility::conversions::to_string_t("Traffic Tickets")) m_value = eCleanCategory::CleanCategory_Traffic Tickets;
    if (s == utility::conversions::to_string_t("Maintenance &amp; Repairs")) m_value = eCleanCategory::CleanCategory_Maintenance &amp; Repairs;
    if (s == utility::conversions::to_string_t("Auto Payment")) m_value = eCleanCategory::CleanCategory_Auto Payment;
    if (s == utility::conversions::to_string_t("Auto Insurance")) m_value = eCleanCategory::CleanCategory_Auto Insurance;
    if (s == utility::conversions::to_string_t("Public Transportation")) m_value = eCleanCategory::CleanCategory_Public Transportation;
    if (s == utility::conversions::to_string_t("Other Car")) m_value = eCleanCategory::CleanCategory_Other Car;
    if (s == utility::conversions::to_string_t("Taxi")) m_value = eCleanCategory::CleanCategory_Taxi;
    if (s == utility::conversions::to_string_t("Boat")) m_value = eCleanCategory::CleanCategory_Boat;
    if (s == utility::conversions::to_string_t("Air Travel")) m_value = eCleanCategory::CleanCategory_Air Travel;
    if (s == utility::conversions::to_string_t("Lodging")) m_value = eCleanCategory::CleanCategory_Lodging;
    if (s == utility::conversions::to_string_t("Ride Share &amp; Rental")) m_value = eCleanCategory::CleanCategory_Ride Share &amp; Rental;
    if (s == utility::conversions::to_string_t("Other Travel")) m_value = eCleanCategory::CleanCategory_Other Travel;
    if (s == utility::conversions::to_string_t("Account Maintenance")) m_value = eCleanCategory::CleanCategory_Account Maintenance;
    if (s == utility::conversions::to_string_t("Overdraft Fee")) m_value = eCleanCategory::CleanCategory_Overdraft Fee;
    if (s == utility::conversions::to_string_t("Insufficient Funds Fee")) m_value = eCleanCategory::CleanCategory_Insufficient Funds Fee;
    if (s == utility::conversions::to_string_t("ATM Fee")) m_value = eCleanCategory::CleanCategory_ATM Fee;
    if (s == utility::conversions::to_string_t("Check Order Fee")) m_value = eCleanCategory::CleanCategory_Check Order Fee;
    if (s == utility::conversions::to_string_t("Interest Charged Fee")) m_value = eCleanCategory::CleanCategory_Interest Charged Fee;
    if (s == utility::conversions::to_string_t("Foreign Transaction Fee")) m_value = eCleanCategory::CleanCategory_Foreign Transaction Fee;
    if (s == utility::conversions::to_string_t("Wire Fee")) m_value = eCleanCategory::CleanCategory_Wire Fee;
    if (s == utility::conversions::to_string_t("Excessive Transactions Fee")) m_value = eCleanCategory::CleanCategory_Excessive Transactions Fee;
    if (s == utility::conversions::to_string_t("Late Fee")) m_value = eCleanCategory::CleanCategory_Late Fee;
    if (s == utility::conversions::to_string_t("Card Membership Fee")) m_value = eCleanCategory::CleanCategory_Card Membership Fee;
    if (s == utility::conversions::to_string_t("Other Fee")) m_value = eCleanCategory::CleanCategory_Other Fee;
    if (s == utility::conversions::to_string_t("Rent")) m_value = eCleanCategory::CleanCategory_Rent;
    if (s == utility::conversions::to_string_t("Mortgage")) m_value = eCleanCategory::CleanCategory_Mortgage;
    if (s == utility::conversions::to_string_t("Other Housing")) m_value = eCleanCategory::CleanCategory_Other Housing;
    if (s == utility::conversions::to_string_t("Rent Reimbursement")) m_value = eCleanCategory::CleanCategory_Rent Reimbursement;
    if (s == utility::conversions::to_string_t("Yard &amp; Garden")) m_value = eCleanCategory::CleanCategory_Yard &amp; Garden;
    if (s == utility::conversions::to_string_t("Credit card payment")) m_value = eCleanCategory::CleanCategory_Credit card payment;
    if (s == utility::conversions::to_string_t("ATM Withdrawals")) m_value = eCleanCategory::CleanCategory_ATM Withdrawals;
    if (s == utility::conversions::to_string_t("Internal Transfer")) m_value = eCleanCategory::CleanCategory_Internal Transfer;
    if (s == utility::conversions::to_string_t("External Transfer")) m_value = eCleanCategory::CleanCategory_External Transfer;
    if (s == utility::conversions::to_string_t("Other Transfer")) m_value = eCleanCategory::CleanCategory_Other Transfer;
    if (s == utility::conversions::to_string_t("Loan Payment")) m_value = eCleanCategory::CleanCategory_Loan Payment;
    if (s == utility::conversions::to_string_t("Services")) m_value = eCleanCategory::CleanCategory_Services;
    if (s == utility::conversions::to_string_t("Legal Services")) m_value = eCleanCategory::CleanCategory_Legal Services;
    if (s == utility::conversions::to_string_t("Accounting Services")) m_value = eCleanCategory::CleanCategory_Accounting Services;
    if (s == utility::conversions::to_string_t("Real Estate Services")) m_value = eCleanCategory::CleanCategory_Real Estate Services;
    if (s == utility::conversions::to_string_t("Business Services")) m_value = eCleanCategory::CleanCategory_Business Services;
    if (s == utility::conversions::to_string_t("Computer Services")) m_value = eCleanCategory::CleanCategory_Computer Services;
    if (s == utility::conversions::to_string_t("Online Subscriptions")) m_value = eCleanCategory::CleanCategory_Online Subscriptions;
    if (s == utility::conversions::to_string_t("Financial Services")) m_value = eCleanCategory::CleanCategory_Financial Services;
    if (s == utility::conversions::to_string_t("Cleaning Services")) m_value = eCleanCategory::CleanCategory_Cleaning Services;
    if (s == utility::conversions::to_string_t("Internet")) m_value = eCleanCategory::CleanCategory_Internet;
    if (s == utility::conversions::to_string_t("Home Insurance")) m_value = eCleanCategory::CleanCategory_Home Insurance;
    if (s == utility::conversions::to_string_t("Renter&#39;s Insurance")) m_value = eCleanCategory::CleanCategory_Renter&#39;s Insurance;
    if (s == utility::conversions::to_string_t("Life Insurance")) m_value = eCleanCategory::CleanCategory_Life Insurance;
    if (s == utility::conversions::to_string_t("Other Insurance")) m_value = eCleanCategory::CleanCategory_Other Insurance;
    if (s == utility::conversions::to_string_t("Phone Bill")) m_value = eCleanCategory::CleanCategory_Phone Bill;
    if (s == utility::conversions::to_string_t("Utilities")) m_value = eCleanCategory::CleanCategory_Utilities;
    if (s == utility::conversions::to_string_t("TV")) m_value = eCleanCategory::CleanCategory_TV;
    if (s == utility::conversions::to_string_t("Other Bills")) m_value = eCleanCategory::CleanCategory_Other Bills;
    if (s == utility::conversions::to_string_t("Paycheck")) m_value = eCleanCategory::CleanCategory_Paycheck;
    if (s == utility::conversions::to_string_t("Interest")) m_value = eCleanCategory::CleanCategory_Interest;
    if (s == utility::conversions::to_string_t("Reimbursement")) m_value = eCleanCategory::CleanCategory_Reimbursement;
    if (s == utility::conversions::to_string_t("Other Income")) m_value = eCleanCategory::CleanCategory_Other Income;
    if (s == utility::conversions::to_string_t("Tuition")) m_value = eCleanCategory::CleanCategory_Tuition;
    if (s == utility::conversions::to_string_t("Student Loan")) m_value = eCleanCategory::CleanCategory_Student Loan;
    if (s == utility::conversions::to_string_t("Other Education")) m_value = eCleanCategory::CleanCategory_Other Education;
    if (s == utility::conversions::to_string_t("Health Insurance")) m_value = eCleanCategory::CleanCategory_Health Insurance;
    if (s == utility::conversions::to_string_t("Gym")) m_value = eCleanCategory::CleanCategory_Gym;
    if (s == utility::conversions::to_string_t("Dentist")) m_value = eCleanCategory::CleanCategory_Dentist;
    if (s == utility::conversions::to_string_t("Doctor")) m_value = eCleanCategory::CleanCategory_Doctor;
    if (s == utility::conversions::to_string_t("Pharmacy")) m_value = eCleanCategory::CleanCategory_Pharmacy;
    if (s == utility::conversions::to_string_t("Medical Labs")) m_value = eCleanCategory::CleanCategory_Medical Labs;
    if (s == utility::conversions::to_string_t("Barber and Salon")) m_value = eCleanCategory::CleanCategory_Barber and Salon;
    if (s == utility::conversions::to_string_t("Spa")) m_value = eCleanCategory::CleanCategory_Spa;
    if (s == utility::conversions::to_string_t("Nail and Skin")) m_value = eCleanCategory::CleanCategory_Nail and Skin;
    if (s == utility::conversions::to_string_t("Other Health &amp; Fitness")) m_value = eCleanCategory::CleanCategory_Other Health &amp; Fitness;
    if (s == utility::conversions::to_string_t("Groceries")) m_value = eCleanCategory::CleanCategory_Groceries;
    if (s == utility::conversions::to_string_t("Coffee")) m_value = eCleanCategory::CleanCategory_Coffee;
    if (s == utility::conversions::to_string_t("Restaurants")) m_value = eCleanCategory::CleanCategory_Restaurants;
    if (s == utility::conversions::to_string_t("Alcohol")) m_value = eCleanCategory::CleanCategory_Alcohol;
    if (s == utility::conversions::to_string_t("Bars &amp; Clubs")) m_value = eCleanCategory::CleanCategory_Bars &amp; Clubs;
    if (s == utility::conversions::to_string_t("Other Food &amp; Dining")) m_value = eCleanCategory::CleanCategory_Other Food &amp; Dining;
    if (s == utility::conversions::to_string_t("Clothes &amp; Apparel")) m_value = eCleanCategory::CleanCategory_Clothes &amp; Apparel;
    if (s == utility::conversions::to_string_t("Sporting Goods")) m_value = eCleanCategory::CleanCategory_Sporting Goods;
    if (s == utility::conversions::to_string_t("Electronics")) m_value = eCleanCategory::CleanCategory_Electronics;
    if (s == utility::conversions::to_string_t("Games")) m_value = eCleanCategory::CleanCategory_Games;
    if (s == utility::conversions::to_string_t("Tobacco &amp; Vaping")) m_value = eCleanCategory::CleanCategory_Tobacco &amp; Vaping;
    if (s == utility::conversions::to_string_t("Cannabis")) m_value = eCleanCategory::CleanCategory_Cannabis;
    if (s == utility::conversions::to_string_t("Beauty")) m_value = eCleanCategory::CleanCategory_Beauty;
    if (s == utility::conversions::to_string_t("Books")) m_value = eCleanCategory::CleanCategory_Books;
    if (s == utility::conversions::to_string_t("Business Equipment")) m_value = eCleanCategory::CleanCategory_Business Equipment;
    if (s == utility::conversions::to_string_t("Home Hardware")) m_value = eCleanCategory::CleanCategory_Home Hardware;
    if (s == utility::conversions::to_string_t("Shipping")) m_value = eCleanCategory::CleanCategory_Shipping;
    if (s == utility::conversions::to_string_t("Software")) m_value = eCleanCategory::CleanCategory_Software;
    if (s == utility::conversions::to_string_t("Guns &amp; Weapons")) m_value = eCleanCategory::CleanCategory_Guns &amp; Weapons;
    if (s == utility::conversions::to_string_t("Taxes")) m_value = eCleanCategory::CleanCategory_Taxes;
    if (s == utility::conversions::to_string_t("Government Services")) m_value = eCleanCategory::CleanCategory_Government Services;
    if (s == utility::conversions::to_string_t("Fines")) m_value = eCleanCategory::CleanCategory_Fines;
    if (s == utility::conversions::to_string_t("Gifts &amp; Donations")) m_value = eCleanCategory::CleanCategory_Gifts &amp; Donations;
    if (s == utility::conversions::to_string_t("Shopping")) m_value = eCleanCategory::CleanCategory_Shopping;
    if (s == utility::conversions::to_string_t("Other")) m_value = eCleanCategory::CleanCategory_Other;
    if (s == utility::conversions::to_string_t("Pets")) m_value = eCleanCategory::CleanCategory_Pets;
    if (s == utility::conversions::to_string_t("Child Care")) m_value = eCleanCategory::CleanCategory_Child Care;
}

void CleanCategory::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    utility::string_t s;

    
    if (m_value == eCleanCategory::CleanCategory_Arts) s = utility::conversions::to_string_t("Arts");
    if (m_value == eCleanCategory::CleanCategory_Music) s = utility::conversions::to_string_t("Music");
    if (m_value == eCleanCategory::CleanCategory_Movies &amp; Television) s = utility::conversions::to_string_t("Movies &amp; Television");
    if (m_value == eCleanCategory::CleanCategory_Newspaper &amp; Magazines) s = utility::conversions::to_string_t("Newspaper &amp; Magazines");
    if (m_value == eCleanCategory::CleanCategory_Other Entertainment) s = utility::conversions::to_string_t("Other Entertainment");
    if (m_value == eCleanCategory::CleanCategory_Theater) s = utility::conversions::to_string_t("Theater");
    if (m_value == eCleanCategory::CleanCategory_Gambling) s = utility::conversions::to_string_t("Gambling");
    if (m_value == eCleanCategory::CleanCategory_Deposit) s = utility::conversions::to_string_t("Deposit");
    if (m_value == eCleanCategory::CleanCategory_Withdrawal) s = utility::conversions::to_string_t("Withdrawal");
    if (m_value == eCleanCategory::CleanCategory_Dividends) s = utility::conversions::to_string_t("Dividends");
    if (m_value == eCleanCategory::CleanCategory_Buy) s = utility::conversions::to_string_t("Buy");
    if (m_value == eCleanCategory::CleanCategory_Sell) s = utility::conversions::to_string_t("Sell");
    if (m_value == eCleanCategory::CleanCategory_Other Investments) s = utility::conversions::to_string_t("Other Investments");
    if (m_value == eCleanCategory::CleanCategory_Gas &amp; Fuel) s = utility::conversions::to_string_t("Gas &amp; Fuel");
    if (m_value == eCleanCategory::CleanCategory_Car Parts) s = utility::conversions::to_string_t("Car Parts");
    if (m_value == eCleanCategory::CleanCategory_Toll Fee) s = utility::conversions::to_string_t("Toll Fee");
    if (m_value == eCleanCategory::CleanCategory_Parking) s = utility::conversions::to_string_t("Parking");
    if (m_value == eCleanCategory::CleanCategory_Traffic Tickets) s = utility::conversions::to_string_t("Traffic Tickets");
    if (m_value == eCleanCategory::CleanCategory_Maintenance &amp; Repairs) s = utility::conversions::to_string_t("Maintenance &amp; Repairs");
    if (m_value == eCleanCategory::CleanCategory_Auto Payment) s = utility::conversions::to_string_t("Auto Payment");
    if (m_value == eCleanCategory::CleanCategory_Auto Insurance) s = utility::conversions::to_string_t("Auto Insurance");
    if (m_value == eCleanCategory::CleanCategory_Public Transportation) s = utility::conversions::to_string_t("Public Transportation");
    if (m_value == eCleanCategory::CleanCategory_Other Car) s = utility::conversions::to_string_t("Other Car");
    if (m_value == eCleanCategory::CleanCategory_Taxi) s = utility::conversions::to_string_t("Taxi");
    if (m_value == eCleanCategory::CleanCategory_Boat) s = utility::conversions::to_string_t("Boat");
    if (m_value == eCleanCategory::CleanCategory_Air Travel) s = utility::conversions::to_string_t("Air Travel");
    if (m_value == eCleanCategory::CleanCategory_Lodging) s = utility::conversions::to_string_t("Lodging");
    if (m_value == eCleanCategory::CleanCategory_Ride Share &amp; Rental) s = utility::conversions::to_string_t("Ride Share &amp; Rental");
    if (m_value == eCleanCategory::CleanCategory_Other Travel) s = utility::conversions::to_string_t("Other Travel");
    if (m_value == eCleanCategory::CleanCategory_Account Maintenance) s = utility::conversions::to_string_t("Account Maintenance");
    if (m_value == eCleanCategory::CleanCategory_Overdraft Fee) s = utility::conversions::to_string_t("Overdraft Fee");
    if (m_value == eCleanCategory::CleanCategory_Insufficient Funds Fee) s = utility::conversions::to_string_t("Insufficient Funds Fee");
    if (m_value == eCleanCategory::CleanCategory_ATM Fee) s = utility::conversions::to_string_t("ATM Fee");
    if (m_value == eCleanCategory::CleanCategory_Check Order Fee) s = utility::conversions::to_string_t("Check Order Fee");
    if (m_value == eCleanCategory::CleanCategory_Interest Charged Fee) s = utility::conversions::to_string_t("Interest Charged Fee");
    if (m_value == eCleanCategory::CleanCategory_Foreign Transaction Fee) s = utility::conversions::to_string_t("Foreign Transaction Fee");
    if (m_value == eCleanCategory::CleanCategory_Wire Fee) s = utility::conversions::to_string_t("Wire Fee");
    if (m_value == eCleanCategory::CleanCategory_Excessive Transactions Fee) s = utility::conversions::to_string_t("Excessive Transactions Fee");
    if (m_value == eCleanCategory::CleanCategory_Late Fee) s = utility::conversions::to_string_t("Late Fee");
    if (m_value == eCleanCategory::CleanCategory_Card Membership Fee) s = utility::conversions::to_string_t("Card Membership Fee");
    if (m_value == eCleanCategory::CleanCategory_Other Fee) s = utility::conversions::to_string_t("Other Fee");
    if (m_value == eCleanCategory::CleanCategory_Rent) s = utility::conversions::to_string_t("Rent");
    if (m_value == eCleanCategory::CleanCategory_Mortgage) s = utility::conversions::to_string_t("Mortgage");
    if (m_value == eCleanCategory::CleanCategory_Other Housing) s = utility::conversions::to_string_t("Other Housing");
    if (m_value == eCleanCategory::CleanCategory_Rent Reimbursement) s = utility::conversions::to_string_t("Rent Reimbursement");
    if (m_value == eCleanCategory::CleanCategory_Yard &amp; Garden) s = utility::conversions::to_string_t("Yard &amp; Garden");
    if (m_value == eCleanCategory::CleanCategory_Credit card payment) s = utility::conversions::to_string_t("Credit card payment");
    if (m_value == eCleanCategory::CleanCategory_ATM Withdrawals) s = utility::conversions::to_string_t("ATM Withdrawals");
    if (m_value == eCleanCategory::CleanCategory_Internal Transfer) s = utility::conversions::to_string_t("Internal Transfer");
    if (m_value == eCleanCategory::CleanCategory_External Transfer) s = utility::conversions::to_string_t("External Transfer");
    if (m_value == eCleanCategory::CleanCategory_Other Transfer) s = utility::conversions::to_string_t("Other Transfer");
    if (m_value == eCleanCategory::CleanCategory_Loan Payment) s = utility::conversions::to_string_t("Loan Payment");
    if (m_value == eCleanCategory::CleanCategory_Services) s = utility::conversions::to_string_t("Services");
    if (m_value == eCleanCategory::CleanCategory_Legal Services) s = utility::conversions::to_string_t("Legal Services");
    if (m_value == eCleanCategory::CleanCategory_Accounting Services) s = utility::conversions::to_string_t("Accounting Services");
    if (m_value == eCleanCategory::CleanCategory_Real Estate Services) s = utility::conversions::to_string_t("Real Estate Services");
    if (m_value == eCleanCategory::CleanCategory_Business Services) s = utility::conversions::to_string_t("Business Services");
    if (m_value == eCleanCategory::CleanCategory_Computer Services) s = utility::conversions::to_string_t("Computer Services");
    if (m_value == eCleanCategory::CleanCategory_Online Subscriptions) s = utility::conversions::to_string_t("Online Subscriptions");
    if (m_value == eCleanCategory::CleanCategory_Financial Services) s = utility::conversions::to_string_t("Financial Services");
    if (m_value == eCleanCategory::CleanCategory_Cleaning Services) s = utility::conversions::to_string_t("Cleaning Services");
    if (m_value == eCleanCategory::CleanCategory_Internet) s = utility::conversions::to_string_t("Internet");
    if (m_value == eCleanCategory::CleanCategory_Home Insurance) s = utility::conversions::to_string_t("Home Insurance");
    if (m_value == eCleanCategory::CleanCategory_Renter&#39;s Insurance) s = utility::conversions::to_string_t("Renter&#39;s Insurance");
    if (m_value == eCleanCategory::CleanCategory_Life Insurance) s = utility::conversions::to_string_t("Life Insurance");
    if (m_value == eCleanCategory::CleanCategory_Other Insurance) s = utility::conversions::to_string_t("Other Insurance");
    if (m_value == eCleanCategory::CleanCategory_Phone Bill) s = utility::conversions::to_string_t("Phone Bill");
    if (m_value == eCleanCategory::CleanCategory_Utilities) s = utility::conversions::to_string_t("Utilities");
    if (m_value == eCleanCategory::CleanCategory_TV) s = utility::conversions::to_string_t("TV");
    if (m_value == eCleanCategory::CleanCategory_Other Bills) s = utility::conversions::to_string_t("Other Bills");
    if (m_value == eCleanCategory::CleanCategory_Paycheck) s = utility::conversions::to_string_t("Paycheck");
    if (m_value == eCleanCategory::CleanCategory_Interest) s = utility::conversions::to_string_t("Interest");
    if (m_value == eCleanCategory::CleanCategory_Reimbursement) s = utility::conversions::to_string_t("Reimbursement");
    if (m_value == eCleanCategory::CleanCategory_Other Income) s = utility::conversions::to_string_t("Other Income");
    if (m_value == eCleanCategory::CleanCategory_Tuition) s = utility::conversions::to_string_t("Tuition");
    if (m_value == eCleanCategory::CleanCategory_Student Loan) s = utility::conversions::to_string_t("Student Loan");
    if (m_value == eCleanCategory::CleanCategory_Other Education) s = utility::conversions::to_string_t("Other Education");
    if (m_value == eCleanCategory::CleanCategory_Health Insurance) s = utility::conversions::to_string_t("Health Insurance");
    if (m_value == eCleanCategory::CleanCategory_Gym) s = utility::conversions::to_string_t("Gym");
    if (m_value == eCleanCategory::CleanCategory_Dentist) s = utility::conversions::to_string_t("Dentist");
    if (m_value == eCleanCategory::CleanCategory_Doctor) s = utility::conversions::to_string_t("Doctor");
    if (m_value == eCleanCategory::CleanCategory_Pharmacy) s = utility::conversions::to_string_t("Pharmacy");
    if (m_value == eCleanCategory::CleanCategory_Medical Labs) s = utility::conversions::to_string_t("Medical Labs");
    if (m_value == eCleanCategory::CleanCategory_Barber and Salon) s = utility::conversions::to_string_t("Barber and Salon");
    if (m_value == eCleanCategory::CleanCategory_Spa) s = utility::conversions::to_string_t("Spa");
    if (m_value == eCleanCategory::CleanCategory_Nail and Skin) s = utility::conversions::to_string_t("Nail and Skin");
    if (m_value == eCleanCategory::CleanCategory_Other Health &amp; Fitness) s = utility::conversions::to_string_t("Other Health &amp; Fitness");
    if (m_value == eCleanCategory::CleanCategory_Groceries) s = utility::conversions::to_string_t("Groceries");
    if (m_value == eCleanCategory::CleanCategory_Coffee) s = utility::conversions::to_string_t("Coffee");
    if (m_value == eCleanCategory::CleanCategory_Restaurants) s = utility::conversions::to_string_t("Restaurants");
    if (m_value == eCleanCategory::CleanCategory_Alcohol) s = utility::conversions::to_string_t("Alcohol");
    if (m_value == eCleanCategory::CleanCategory_Bars &amp; Clubs) s = utility::conversions::to_string_t("Bars &amp; Clubs");
    if (m_value == eCleanCategory::CleanCategory_Other Food &amp; Dining) s = utility::conversions::to_string_t("Other Food &amp; Dining");
    if (m_value == eCleanCategory::CleanCategory_Clothes &amp; Apparel) s = utility::conversions::to_string_t("Clothes &amp; Apparel");
    if (m_value == eCleanCategory::CleanCategory_Sporting Goods) s = utility::conversions::to_string_t("Sporting Goods");
    if (m_value == eCleanCategory::CleanCategory_Electronics) s = utility::conversions::to_string_t("Electronics");
    if (m_value == eCleanCategory::CleanCategory_Games) s = utility::conversions::to_string_t("Games");
    if (m_value == eCleanCategory::CleanCategory_Tobacco &amp; Vaping) s = utility::conversions::to_string_t("Tobacco &amp; Vaping");
    if (m_value == eCleanCategory::CleanCategory_Cannabis) s = utility::conversions::to_string_t("Cannabis");
    if (m_value == eCleanCategory::CleanCategory_Beauty) s = utility::conversions::to_string_t("Beauty");
    if (m_value == eCleanCategory::CleanCategory_Books) s = utility::conversions::to_string_t("Books");
    if (m_value == eCleanCategory::CleanCategory_Business Equipment) s = utility::conversions::to_string_t("Business Equipment");
    if (m_value == eCleanCategory::CleanCategory_Home Hardware) s = utility::conversions::to_string_t("Home Hardware");
    if (m_value == eCleanCategory::CleanCategory_Shipping) s = utility::conversions::to_string_t("Shipping");
    if (m_value == eCleanCategory::CleanCategory_Software) s = utility::conversions::to_string_t("Software");
    if (m_value == eCleanCategory::CleanCategory_Guns &amp; Weapons) s = utility::conversions::to_string_t("Guns &amp; Weapons");
    if (m_value == eCleanCategory::CleanCategory_Taxes) s = utility::conversions::to_string_t("Taxes");
    if (m_value == eCleanCategory::CleanCategory_Government Services) s = utility::conversions::to_string_t("Government Services");
    if (m_value == eCleanCategory::CleanCategory_Fines) s = utility::conversions::to_string_t("Fines");
    if (m_value == eCleanCategory::CleanCategory_Gifts &amp; Donations) s = utility::conversions::to_string_t("Gifts &amp; Donations");
    if (m_value == eCleanCategory::CleanCategory_Shopping) s = utility::conversions::to_string_t("Shopping");
    if (m_value == eCleanCategory::CleanCategory_Other) s = utility::conversions::to_string_t("Other");
    if (m_value == eCleanCategory::CleanCategory_Pets) s = utility::conversions::to_string_t("Pets");
    if (m_value == eCleanCategory::CleanCategory_Child Care) s = utility::conversions::to_string_t("Child Care");

    multipart->add(ModelBase::toHttpContent(namePrefix, s));
}

void CleanCategory::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        utility::string_t s;
        s = ModelBase::stringFromHttpContent(multipart->getContent(namePrefix));
        eCleanCategory v;
        
        
        if (s == utility::conversions::to_string_t("Arts")) v = eCleanCategory::CleanCategory_Arts;
        if (s == utility::conversions::to_string_t("Music")) v = eCleanCategory::CleanCategory_Music;
        if (s == utility::conversions::to_string_t("Movies &amp; Television")) v = eCleanCategory::CleanCategory_Movies &amp; Television;
        if (s == utility::conversions::to_string_t("Newspaper &amp; Magazines")) v = eCleanCategory::CleanCategory_Newspaper &amp; Magazines;
        if (s == utility::conversions::to_string_t("Other Entertainment")) v = eCleanCategory::CleanCategory_Other Entertainment;
        if (s == utility::conversions::to_string_t("Theater")) v = eCleanCategory::CleanCategory_Theater;
        if (s == utility::conversions::to_string_t("Gambling")) v = eCleanCategory::CleanCategory_Gambling;
        if (s == utility::conversions::to_string_t("Deposit")) v = eCleanCategory::CleanCategory_Deposit;
        if (s == utility::conversions::to_string_t("Withdrawal")) v = eCleanCategory::CleanCategory_Withdrawal;
        if (s == utility::conversions::to_string_t("Dividends")) v = eCleanCategory::CleanCategory_Dividends;
        if (s == utility::conversions::to_string_t("Buy")) v = eCleanCategory::CleanCategory_Buy;
        if (s == utility::conversions::to_string_t("Sell")) v = eCleanCategory::CleanCategory_Sell;
        if (s == utility::conversions::to_string_t("Other Investments")) v = eCleanCategory::CleanCategory_Other Investments;
        if (s == utility::conversions::to_string_t("Gas &amp; Fuel")) v = eCleanCategory::CleanCategory_Gas &amp; Fuel;
        if (s == utility::conversions::to_string_t("Car Parts")) v = eCleanCategory::CleanCategory_Car Parts;
        if (s == utility::conversions::to_string_t("Toll Fee")) v = eCleanCategory::CleanCategory_Toll Fee;
        if (s == utility::conversions::to_string_t("Parking")) v = eCleanCategory::CleanCategory_Parking;
        if (s == utility::conversions::to_string_t("Traffic Tickets")) v = eCleanCategory::CleanCategory_Traffic Tickets;
        if (s == utility::conversions::to_string_t("Maintenance &amp; Repairs")) v = eCleanCategory::CleanCategory_Maintenance &amp; Repairs;
        if (s == utility::conversions::to_string_t("Auto Payment")) v = eCleanCategory::CleanCategory_Auto Payment;
        if (s == utility::conversions::to_string_t("Auto Insurance")) v = eCleanCategory::CleanCategory_Auto Insurance;
        if (s == utility::conversions::to_string_t("Public Transportation")) v = eCleanCategory::CleanCategory_Public Transportation;
        if (s == utility::conversions::to_string_t("Other Car")) v = eCleanCategory::CleanCategory_Other Car;
        if (s == utility::conversions::to_string_t("Taxi")) v = eCleanCategory::CleanCategory_Taxi;
        if (s == utility::conversions::to_string_t("Boat")) v = eCleanCategory::CleanCategory_Boat;
        if (s == utility::conversions::to_string_t("Air Travel")) v = eCleanCategory::CleanCategory_Air Travel;
        if (s == utility::conversions::to_string_t("Lodging")) v = eCleanCategory::CleanCategory_Lodging;
        if (s == utility::conversions::to_string_t("Ride Share &amp; Rental")) v = eCleanCategory::CleanCategory_Ride Share &amp; Rental;
        if (s == utility::conversions::to_string_t("Other Travel")) v = eCleanCategory::CleanCategory_Other Travel;
        if (s == utility::conversions::to_string_t("Account Maintenance")) v = eCleanCategory::CleanCategory_Account Maintenance;
        if (s == utility::conversions::to_string_t("Overdraft Fee")) v = eCleanCategory::CleanCategory_Overdraft Fee;
        if (s == utility::conversions::to_string_t("Insufficient Funds Fee")) v = eCleanCategory::CleanCategory_Insufficient Funds Fee;
        if (s == utility::conversions::to_string_t("ATM Fee")) v = eCleanCategory::CleanCategory_ATM Fee;
        if (s == utility::conversions::to_string_t("Check Order Fee")) v = eCleanCategory::CleanCategory_Check Order Fee;
        if (s == utility::conversions::to_string_t("Interest Charged Fee")) v = eCleanCategory::CleanCategory_Interest Charged Fee;
        if (s == utility::conversions::to_string_t("Foreign Transaction Fee")) v = eCleanCategory::CleanCategory_Foreign Transaction Fee;
        if (s == utility::conversions::to_string_t("Wire Fee")) v = eCleanCategory::CleanCategory_Wire Fee;
        if (s == utility::conversions::to_string_t("Excessive Transactions Fee")) v = eCleanCategory::CleanCategory_Excessive Transactions Fee;
        if (s == utility::conversions::to_string_t("Late Fee")) v = eCleanCategory::CleanCategory_Late Fee;
        if (s == utility::conversions::to_string_t("Card Membership Fee")) v = eCleanCategory::CleanCategory_Card Membership Fee;
        if (s == utility::conversions::to_string_t("Other Fee")) v = eCleanCategory::CleanCategory_Other Fee;
        if (s == utility::conversions::to_string_t("Rent")) v = eCleanCategory::CleanCategory_Rent;
        if (s == utility::conversions::to_string_t("Mortgage")) v = eCleanCategory::CleanCategory_Mortgage;
        if (s == utility::conversions::to_string_t("Other Housing")) v = eCleanCategory::CleanCategory_Other Housing;
        if (s == utility::conversions::to_string_t("Rent Reimbursement")) v = eCleanCategory::CleanCategory_Rent Reimbursement;
        if (s == utility::conversions::to_string_t("Yard &amp; Garden")) v = eCleanCategory::CleanCategory_Yard &amp; Garden;
        if (s == utility::conversions::to_string_t("Credit card payment")) v = eCleanCategory::CleanCategory_Credit card payment;
        if (s == utility::conversions::to_string_t("ATM Withdrawals")) v = eCleanCategory::CleanCategory_ATM Withdrawals;
        if (s == utility::conversions::to_string_t("Internal Transfer")) v = eCleanCategory::CleanCategory_Internal Transfer;
        if (s == utility::conversions::to_string_t("External Transfer")) v = eCleanCategory::CleanCategory_External Transfer;
        if (s == utility::conversions::to_string_t("Other Transfer")) v = eCleanCategory::CleanCategory_Other Transfer;
        if (s == utility::conversions::to_string_t("Loan Payment")) v = eCleanCategory::CleanCategory_Loan Payment;
        if (s == utility::conversions::to_string_t("Services")) v = eCleanCategory::CleanCategory_Services;
        if (s == utility::conversions::to_string_t("Legal Services")) v = eCleanCategory::CleanCategory_Legal Services;
        if (s == utility::conversions::to_string_t("Accounting Services")) v = eCleanCategory::CleanCategory_Accounting Services;
        if (s == utility::conversions::to_string_t("Real Estate Services")) v = eCleanCategory::CleanCategory_Real Estate Services;
        if (s == utility::conversions::to_string_t("Business Services")) v = eCleanCategory::CleanCategory_Business Services;
        if (s == utility::conversions::to_string_t("Computer Services")) v = eCleanCategory::CleanCategory_Computer Services;
        if (s == utility::conversions::to_string_t("Online Subscriptions")) v = eCleanCategory::CleanCategory_Online Subscriptions;
        if (s == utility::conversions::to_string_t("Financial Services")) v = eCleanCategory::CleanCategory_Financial Services;
        if (s == utility::conversions::to_string_t("Cleaning Services")) v = eCleanCategory::CleanCategory_Cleaning Services;
        if (s == utility::conversions::to_string_t("Internet")) v = eCleanCategory::CleanCategory_Internet;
        if (s == utility::conversions::to_string_t("Home Insurance")) v = eCleanCategory::CleanCategory_Home Insurance;
        if (s == utility::conversions::to_string_t("Renter&#39;s Insurance")) v = eCleanCategory::CleanCategory_Renter&#39;s Insurance;
        if (s == utility::conversions::to_string_t("Life Insurance")) v = eCleanCategory::CleanCategory_Life Insurance;
        if (s == utility::conversions::to_string_t("Other Insurance")) v = eCleanCategory::CleanCategory_Other Insurance;
        if (s == utility::conversions::to_string_t("Phone Bill")) v = eCleanCategory::CleanCategory_Phone Bill;
        if (s == utility::conversions::to_string_t("Utilities")) v = eCleanCategory::CleanCategory_Utilities;
        if (s == utility::conversions::to_string_t("TV")) v = eCleanCategory::CleanCategory_TV;
        if (s == utility::conversions::to_string_t("Other Bills")) v = eCleanCategory::CleanCategory_Other Bills;
        if (s == utility::conversions::to_string_t("Paycheck")) v = eCleanCategory::CleanCategory_Paycheck;
        if (s == utility::conversions::to_string_t("Interest")) v = eCleanCategory::CleanCategory_Interest;
        if (s == utility::conversions::to_string_t("Reimbursement")) v = eCleanCategory::CleanCategory_Reimbursement;
        if (s == utility::conversions::to_string_t("Other Income")) v = eCleanCategory::CleanCategory_Other Income;
        if (s == utility::conversions::to_string_t("Tuition")) v = eCleanCategory::CleanCategory_Tuition;
        if (s == utility::conversions::to_string_t("Student Loan")) v = eCleanCategory::CleanCategory_Student Loan;
        if (s == utility::conversions::to_string_t("Other Education")) v = eCleanCategory::CleanCategory_Other Education;
        if (s == utility::conversions::to_string_t("Health Insurance")) v = eCleanCategory::CleanCategory_Health Insurance;
        if (s == utility::conversions::to_string_t("Gym")) v = eCleanCategory::CleanCategory_Gym;
        if (s == utility::conversions::to_string_t("Dentist")) v = eCleanCategory::CleanCategory_Dentist;
        if (s == utility::conversions::to_string_t("Doctor")) v = eCleanCategory::CleanCategory_Doctor;
        if (s == utility::conversions::to_string_t("Pharmacy")) v = eCleanCategory::CleanCategory_Pharmacy;
        if (s == utility::conversions::to_string_t("Medical Labs")) v = eCleanCategory::CleanCategory_Medical Labs;
        if (s == utility::conversions::to_string_t("Barber and Salon")) v = eCleanCategory::CleanCategory_Barber and Salon;
        if (s == utility::conversions::to_string_t("Spa")) v = eCleanCategory::CleanCategory_Spa;
        if (s == utility::conversions::to_string_t("Nail and Skin")) v = eCleanCategory::CleanCategory_Nail and Skin;
        if (s == utility::conversions::to_string_t("Other Health &amp; Fitness")) v = eCleanCategory::CleanCategory_Other Health &amp; Fitness;
        if (s == utility::conversions::to_string_t("Groceries")) v = eCleanCategory::CleanCategory_Groceries;
        if (s == utility::conversions::to_string_t("Coffee")) v = eCleanCategory::CleanCategory_Coffee;
        if (s == utility::conversions::to_string_t("Restaurants")) v = eCleanCategory::CleanCategory_Restaurants;
        if (s == utility::conversions::to_string_t("Alcohol")) v = eCleanCategory::CleanCategory_Alcohol;
        if (s == utility::conversions::to_string_t("Bars &amp; Clubs")) v = eCleanCategory::CleanCategory_Bars &amp; Clubs;
        if (s == utility::conversions::to_string_t("Other Food &amp; Dining")) v = eCleanCategory::CleanCategory_Other Food &amp; Dining;
        if (s == utility::conversions::to_string_t("Clothes &amp; Apparel")) v = eCleanCategory::CleanCategory_Clothes &amp; Apparel;
        if (s == utility::conversions::to_string_t("Sporting Goods")) v = eCleanCategory::CleanCategory_Sporting Goods;
        if (s == utility::conversions::to_string_t("Electronics")) v = eCleanCategory::CleanCategory_Electronics;
        if (s == utility::conversions::to_string_t("Games")) v = eCleanCategory::CleanCategory_Games;
        if (s == utility::conversions::to_string_t("Tobacco &amp; Vaping")) v = eCleanCategory::CleanCategory_Tobacco &amp; Vaping;
        if (s == utility::conversions::to_string_t("Cannabis")) v = eCleanCategory::CleanCategory_Cannabis;
        if (s == utility::conversions::to_string_t("Beauty")) v = eCleanCategory::CleanCategory_Beauty;
        if (s == utility::conversions::to_string_t("Books")) v = eCleanCategory::CleanCategory_Books;
        if (s == utility::conversions::to_string_t("Business Equipment")) v = eCleanCategory::CleanCategory_Business Equipment;
        if (s == utility::conversions::to_string_t("Home Hardware")) v = eCleanCategory::CleanCategory_Home Hardware;
        if (s == utility::conversions::to_string_t("Shipping")) v = eCleanCategory::CleanCategory_Shipping;
        if (s == utility::conversions::to_string_t("Software")) v = eCleanCategory::CleanCategory_Software;
        if (s == utility::conversions::to_string_t("Guns &amp; Weapons")) v = eCleanCategory::CleanCategory_Guns &amp; Weapons;
        if (s == utility::conversions::to_string_t("Taxes")) v = eCleanCategory::CleanCategory_Taxes;
        if (s == utility::conversions::to_string_t("Government Services")) v = eCleanCategory::CleanCategory_Government Services;
        if (s == utility::conversions::to_string_t("Fines")) v = eCleanCategory::CleanCategory_Fines;
        if (s == utility::conversions::to_string_t("Gifts &amp; Donations")) v = eCleanCategory::CleanCategory_Gifts &amp; Donations;
        if (s == utility::conversions::to_string_t("Shopping")) v = eCleanCategory::CleanCategory_Shopping;
        if (s == utility::conversions::to_string_t("Other")) v = eCleanCategory::CleanCategory_Other;
        if (s == utility::conversions::to_string_t("Pets")) v = eCleanCategory::CleanCategory_Pets;
        if (s == utility::conversions::to_string_t("Child Care")) v = eCleanCategory::CleanCategory_Child Care;

        setValue(v);
    }
}

CleanCategory::eCleanCategory CleanCategory::getValue() const
{
   return m_value;
}

void CleanCategory::setValue(CleanCategory::eCleanCategory const value)
{
   m_value = value;
}


}
}
}
}


