/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CreateWebhookResponse.h"

namespace dev {
namespace haven {
namespace client {
namespace model {




CreateWebhookResponse::CreateWebhookResponse()
{
}

CreateWebhookResponse::~CreateWebhookResponse()
{
}

void CreateWebhookResponse::validate()
{
    // TODO: implement validation
}

web::json::value CreateWebhookResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("webhook")] = ModelBase::toJson(m_Webhook);

    return val;
}

void CreateWebhookResponse::fromJson(const web::json::value& val)
{
    std::shared_ptr<Webhook> newWebhook(new Webhook());
    newWebhook->fromJson(val.at(utility::conversions::to_string_t("webhook")));
    setWebhook( newWebhook );
}

void CreateWebhookResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    m_Webhook->toMultipart(multipart, utility::conversions::to_string_t("webhook."));
}

void CreateWebhookResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    std::shared_ptr<Webhook> newWebhook(new Webhook());
    newWebhook->fromMultiPart(multipart, utility::conversions::to_string_t("webhook."));
    setWebhook( newWebhook );
}

std::shared_ptr<Webhook> CreateWebhookResponse::getWebhook() const
{
    return m_Webhook;
}

void CreateWebhookResponse::setWebhook(const std::shared_ptr<Webhook>& value)
{
    m_Webhook = value;
    
}

}
}
}
}


