/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateWebhookRequest.h
 *
 * 
 */

#ifndef DEV_HAVEN_CLIENT_MODEL_CreateWebhookRequest_H_
#define DEV_HAVEN_CLIENT_MODEL_CreateWebhookRequest_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "WebhookSubscription.h"
#include <vector>

namespace dev {
namespace haven {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  CreateWebhookRequest
    : public ModelBase
{
public:
    CreateWebhookRequest();
    virtual ~CreateWebhookRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateWebhookRequest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCallback() const;
    
    void setCallback(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<WebhookSubscription>>& getSubscriptions();
    
    void setSubscriptions(const std::vector<std::shared_ptr<WebhookSubscription>>& value);


protected:
    utility::string_t m_Callback;
        std::vector<std::shared_ptr<WebhookSubscription>> m_Subscriptions;
    };


}
}
}
}

#endif /* DEV_HAVEN_CLIENT_MODEL_CreateWebhookRequest_H_ */
