/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CreateWebhookRequest.h"

namespace dev {
namespace haven {
namespace client {
namespace model {




CreateWebhookRequest::CreateWebhookRequest()
{
    m_Callback = utility::conversions::to_string_t("");
}

CreateWebhookRequest::~CreateWebhookRequest()
{
}

void CreateWebhookRequest::validate()
{
    // TODO: implement validation
}

web::json::value CreateWebhookRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("callback")] = ModelBase::toJson(m_Callback);
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Subscriptions )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val[utility::conversions::to_string_t("subscriptions")] = web::json::value::array(jsonArray);
    }

    return val;
}

void CreateWebhookRequest::fromJson(const web::json::value& val)
{
    setCallback(ModelBase::stringFromJson(val.at(utility::conversions::to_string_t("callback"))));
    {
        m_Subscriptions.clear();
        std::vector<web::json::value> jsonArray;
        for( auto& item : val.at(utility::conversions::to_string_t("subscriptions")).as_array() )
        {
            if(item.is_null())
            {
                m_Subscriptions.push_back( std::shared_ptr<WebhookSubscription>(nullptr) );
            }
            else
            {
                std::shared_ptr<WebhookSubscription> newItem(new WebhookSubscription());
                newItem->fromJson(item);
                m_Subscriptions.push_back( newItem );
            }
        }
    }
}

void CreateWebhookRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("callback"), m_Callback));
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Subscriptions )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("subscriptions"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
            }
}

void CreateWebhookRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setCallback(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("callback"))));
    {
        m_Subscriptions.clear();

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("subscriptions"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Subscriptions.push_back( std::shared_ptr<WebhookSubscription>(nullptr) );
            }
            else
            {
                std::shared_ptr<WebhookSubscription> newItem(new WebhookSubscription());
                newItem->fromJson(item);
                m_Subscriptions.push_back( newItem );
            }
        }
    }
}

utility::string_t CreateWebhookRequest::getCallback() const
{
    return m_Callback;
}

void CreateWebhookRequest::setCallback(const utility::string_t& value)
{
    m_Callback = value;
    
}

std::vector<std::shared_ptr<WebhookSubscription>>& CreateWebhookRequest::getSubscriptions()
{
    return m_Subscriptions;
}

void CreateWebhookRequest::setSubscriptions(const std::vector<std::shared_ptr<WebhookSubscription>>& value)
{
    m_Subscriptions = value;
    
}

}
}
}
}


