/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EmptyResponse.h
 *
 * 
 */

#ifndef DEV_HAVEN_CLIENT_MODEL_EmptyResponse_H_
#define DEV_HAVEN_CLIENT_MODEL_EmptyResponse_H_


#include "../ModelBase.h"


namespace dev {
namespace haven {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  EmptyResponse
    : public ModelBase
{
public:
    EmptyResponse();
    virtual ~EmptyResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// EmptyResponse members

    /// <summary>
    /// 
    /// </summary>
    int32_t getA() const;
    bool AIsSet() const;
    void unseta();

    void setA(int32_t value);


protected:
    int32_t m_a;
    bool m_aIsSet;
};


}
}
}
}

#endif /* DEV_HAVEN_CLIENT_MODEL_EmptyResponse_H_ */
