/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetMerchantResponse.h
 *
 * 
 */

#ifndef DEV_HAVEN_CLIENT_MODEL_GetMerchantResponse_H_
#define DEV_HAVEN_CLIENT_MODEL_GetMerchantResponse_H_


#include "../ModelBase.h"

#include "Merchant.h"

namespace dev {
namespace haven {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  GetMerchantResponse
    : public ModelBase
{
public:
    GetMerchantResponse();
    virtual ~GetMerchantResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GetMerchantResponse members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Merchant> getMerchant() const;
    bool merchantIsSet() const;
    void unsetMerchant();

    void setMerchant(const std::shared_ptr<Merchant>& value);


protected:
    std::shared_ptr<Merchant> m_Merchant;
    bool m_MerchantIsSet;
};


}
}
}
}

#endif /* DEV_HAVEN_CLIENT_MODEL_GetMerchantResponse_H_ */
