/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Merchant.h
 *
 * 
 */

#ifndef DEV_HAVEN_CLIENT_MODEL_Merchant_H_
#define DEV_HAVEN_CLIENT_MODEL_Merchant_H_


#include "../ModelBase.h"

#include "CleanCategory.h"
#include "OpenHours.h"
#include "Address.h"
#include <cpprest/details/basic_types.h>

namespace dev {
namespace haven {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  Merchant
    : public ModelBase
{
public:
    Merchant();
    virtual ~Merchant();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Merchant members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    
    void setName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Address> getAddress() const;
    bool addressIsSet() const;
    void unsetAddress();

    void setAddress(const std::shared_ptr<Address>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<OpenHours> getHours() const;
    bool hoursIsSet() const;
    void unsetHours();

    void setHours(const std::shared_ptr<OpenHours>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getImage() const;
    bool imageIsSet() const;
    void unsetImage();

    void setImage(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBackgroundImage() const;
    bool backgroundImageIsSet() const;
    void unsetBackgroundImage();

    void setBackgroundImage(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<CleanCategory> getCategory() const;
    
    void setCategory(const std::shared_ptr<CleanCategory>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();

    void setPhone(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();

    void setUrl(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFacebook() const;
    bool facebookIsSet() const;
    void unsetFacebook();

    void setFacebook(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTwitter() const;
    bool twitterIsSet() const;
    void unsetTwitter();

    void setTwitter(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getInstagram() const;
    bool instagramIsSet() const;
    void unsetInstagram();

    void setInstagram(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getYelp() const;
    bool yelpIsSet() const;
    void unsetYelp();

    void setYelp(const utility::string_t& value);


protected:
    utility::string_t m_Name;
        std::shared_ptr<Address> m_Address;
    bool m_AddressIsSet;
    std::shared_ptr<OpenHours> m_Hours;
    bool m_HoursIsSet;
    utility::string_t m_Image;
    bool m_ImageIsSet;
    utility::string_t m_BackgroundImage;
    bool m_BackgroundImageIsSet;
    std::shared_ptr<CleanCategory> m_Category;
        utility::string_t m_Phone;
    bool m_PhoneIsSet;
    utility::string_t m_Url;
    bool m_UrlIsSet;
    utility::string_t m_Facebook;
    bool m_FacebookIsSet;
    utility::string_t m_Twitter;
    bool m_TwitterIsSet;
    utility::string_t m_Instagram;
    bool m_InstagramIsSet;
    utility::string_t m_Yelp;
    bool m_YelpIsSet;
};


}
}
}
}

#endif /* DEV_HAVEN_CLIENT_MODEL_Merchant_H_ */
