/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "OpenHours.h"

namespace dev {
namespace haven {
namespace client {
namespace model {




OpenHours::OpenHours()
{
    m_Description = utility::conversions::to_string_t("");
}

OpenHours::~OpenHours()
{
}

void OpenHours::validate()
{
    // TODO: implement validation
}

web::json::value OpenHours::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("description")] = ModelBase::toJson(m_Description);

    return val;
}

void OpenHours::fromJson(const web::json::value& val)
{
    setDescription(ModelBase::stringFromJson(val.at(utility::conversions::to_string_t("description"))));
}

void OpenHours::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("description"), m_Description));
}

void OpenHours::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setDescription(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("description"))));
}

utility::string_t OpenHours::getDescription() const
{
    return m_Description;
}

void OpenHours::setDescription(const utility::string_t& value)
{
    m_Description = value;
    
}

}
}
}
}


