# coding: utf-8

"""
    Haven Money API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import haven
from haven.models.institution_colors import InstitutionColors  # noqa: E501
from haven.rest import ApiException


class TestInstitutionColors(unittest.TestCase):
    """InstitutionColors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitutionColors(self):
        """Test InstitutionColors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = haven.models.institution_colors.InstitutionColors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
