/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models

import dev.haven.client.models.AccountSubType
import dev.haven.client.models.AccountType
import dev.haven.client.models.Balance

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param user 
 * @param displayName 
 * @param displayNameDetailed 
 * @param institution 
 * @param institutionName 
 * @param accountType 
 * @param accountSubType 
 * @param balance 
 * @param createdAt 
 * @param updatedAt 
 */
data class AccountUpdate (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "user")
    val user: kotlin.String,
    @Json(name = "displayName")
    val displayName: kotlin.String,
    @Json(name = "displayNameDetailed")
    val displayNameDetailed: kotlin.String,
    @Json(name = "institution")
    val institution: kotlin.String,
    @Json(name = "institutionName")
    val institutionName: kotlin.String,
    @Json(name = "accountType")
    val accountType: AccountType,
    @Json(name = "accountSubType")
    val accountSubType: AccountSubType,
    @Json(name = "balance")
    val balance: Balance,
    @Json(name = "createdAt")
    val createdAt: java.time.Instant,
    @Json(name = "updatedAt")
    val updatedAt: java.time.Instant
) {

}

