/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models


import com.squareup.moshi.Json

/**
* 
* Values: AUTO,BROKERAGE,CASH_ISA,CASH_MANAGEMENT,CD,CHECKING,COMMERCIAL,CONSTRUCTION,CONSUMER,CREDIT,CREDIT_CARD,DEPOSITORY,EDUCATION_SAVINGS_ACCOUNT,GIC,HEALTH_REIMBURSEMENT_ARRANGEMENT,HOME,HOME_EQUITY,HSA,IRA,ISA,KEOGH,LIF,LINE_OF_CREDIT,LIRA,LOAN,LRIF,LRSP,MONEY_MARKET,MORTGAGE,MUTUAL_FUND,NON_TAXABLE_BROKERAGE_ACCOUNT,OTHER,OVERDRAFT,PAYPAL,PENSION,PREPAID,PRIF,PROFIT_SHARING_PLAN,RDSP,RECURRING,RESP,RETIREMENT,REWARDS,RLIF,ROTH,ROTH_401K,RRIF,RRSP,SAFE_DEPOSIT,SARSEP,SAVINGS,SEP_IRA,SIMPLE_IRA,SIPP,STOCK_PLAN,STUDENT,TFSA,THRIFT_SAVINGS_PLAN,T_401A,T_401K,T_403B,T_457B,T_529,UGMA,UTMA,VARIABLE_ANNUITY
*/
enum class AccountSubType(val value: kotlin.String){

    @Json(name = "AUTO")
    AUTO("AUTO"),

    @Json(name = "BROKERAGE")
    BROKERAGE("BROKERAGE"),

    @Json(name = "CASH_ISA")
    CASH_ISA("CASH_ISA"),

    @Json(name = "CASH_MANAGEMENT")
    CASH_MANAGEMENT("CASH_MANAGEMENT"),

    @Json(name = "CD")
    CD("CD"),

    @Json(name = "CHECKING")
    CHECKING("CHECKING"),

    @Json(name = "COMMERCIAL")
    COMMERCIAL("COMMERCIAL"),

    @Json(name = "CONSTRUCTION")
    CONSTRUCTION("CONSTRUCTION"),

    @Json(name = "CONSUMER")
    CONSUMER("CONSUMER"),

    @Json(name = "CREDIT")
    CREDIT("CREDIT"),

    @Json(name = "CREDIT_CARD")
    CREDIT_CARD("CREDIT_CARD"),

    @Json(name = "DEPOSITORY")
    DEPOSITORY("DEPOSITORY"),

    @Json(name = "EDUCATION_SAVINGS_ACCOUNT")
    EDUCATION_SAVINGS_ACCOUNT("EDUCATION_SAVINGS_ACCOUNT"),

    @Json(name = "GIC")
    GIC("GIC"),

    @Json(name = "HEALTH_REIMBURSEMENT_ARRANGEMENT")
    HEALTH_REIMBURSEMENT_ARRANGEMENT("HEALTH_REIMBURSEMENT_ARRANGEMENT"),

    @Json(name = "HOME")
    HOME("HOME"),

    @Json(name = "HOME_EQUITY")
    HOME_EQUITY("HOME_EQUITY"),

    @Json(name = "HSA")
    HSA("HSA"),

    @Json(name = "IRA")
    IRA("IRA"),

    @Json(name = "ISA")
    ISA("ISA"),

    @Json(name = "KEOGH")
    KEOGH("KEOGH"),

    @Json(name = "LIF")
    LIF("LIF"),

    @Json(name = "LINE_OF_CREDIT")
    LINE_OF_CREDIT("LINE_OF_CREDIT"),

    @Json(name = "LIRA")
    LIRA("LIRA"),

    @Json(name = "LOAN")
    LOAN("LOAN"),

    @Json(name = "LRIF")
    LRIF("LRIF"),

    @Json(name = "LRSP")
    LRSP("LRSP"),

    @Json(name = "MONEY_MARKET")
    MONEY_MARKET("MONEY_MARKET"),

    @Json(name = "MORTGAGE")
    MORTGAGE("MORTGAGE"),

    @Json(name = "MUTUAL_FUND")
    MUTUAL_FUND("MUTUAL_FUND"),

    @Json(name = "NON_TAXABLE_BROKERAGE_ACCOUNT")
    NON_TAXABLE_BROKERAGE_ACCOUNT("NON_TAXABLE_BROKERAGE_ACCOUNT"),

    @Json(name = "OTHER")
    OTHER("OTHER"),

    @Json(name = "OVERDRAFT")
    OVERDRAFT("OVERDRAFT"),

    @Json(name = "PAYPAL")
    PAYPAL("PAYPAL"),

    @Json(name = "PENSION")
    PENSION("PENSION"),

    @Json(name = "PREPAID")
    PREPAID("PREPAID"),

    @Json(name = "PRIF")
    PRIF("PRIF"),

    @Json(name = "PROFIT_SHARING_PLAN")
    PROFIT_SHARING_PLAN("PROFIT_SHARING_PLAN"),

    @Json(name = "RDSP")
    RDSP("RDSP"),

    @Json(name = "RECURRING")
    RECURRING("RECURRING"),

    @Json(name = "RESP")
    RESP("RESP"),

    @Json(name = "RETIREMENT")
    RETIREMENT("RETIREMENT"),

    @Json(name = "REWARDS")
    REWARDS("REWARDS"),

    @Json(name = "RLIF")
    RLIF("RLIF"),

    @Json(name = "ROTH")
    ROTH("ROTH"),

    @Json(name = "ROTH_401K")
    ROTH_401K("ROTH_401K"),

    @Json(name = "RRIF")
    RRIF("RRIF"),

    @Json(name = "RRSP")
    RRSP("RRSP"),

    @Json(name = "SAFE_DEPOSIT")
    SAFE_DEPOSIT("SAFE_DEPOSIT"),

    @Json(name = "SARSEP")
    SARSEP("SARSEP"),

    @Json(name = "SAVINGS")
    SAVINGS("SAVINGS"),

    @Json(name = "SEP_IRA")
    SEP_IRA("SEP_IRA"),

    @Json(name = "SIMPLE_IRA")
    SIMPLE_IRA("SIMPLE_IRA"),

    @Json(name = "SIPP")
    SIPP("SIPP"),

    @Json(name = "STOCK_PLAN")
    STOCK_PLAN("STOCK_PLAN"),

    @Json(name = "STUDENT")
    STUDENT("STUDENT"),

    @Json(name = "TFSA")
    TFSA("TFSA"),

    @Json(name = "THRIFT_SAVINGS_PLAN")
    THRIFT_SAVINGS_PLAN("THRIFT_SAVINGS_PLAN"),

    @Json(name = "T_401A")
    T_401A("T_401A"),

    @Json(name = "T_401K")
    T_401K("T_401K"),

    @Json(name = "T_403B")
    T_403B("T_403B"),

    @Json(name = "T_457B")
    T_457B("T_457B"),

    @Json(name = "T_529")
    T_529("T_529"),

    @Json(name = "UGMA")
    UGMA("UGMA"),

    @Json(name = "UTMA")
    UTMA("UTMA"),

    @Json(name = "VARIABLE_ANNUITY")
    VARIABLE_ANNUITY("VARIABLE_ANNUITY");

}

