/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models


import com.squareup.moshi.Json

/**
* 
* Values: userMinusExact,userMinusFuzzy,accountMinusExact,accountMinusFuzzy,none
*/
enum class BootstrapStrategy(val value: kotlin.String){

    @Json(name = "user-exact")
    userMinusExact("user-exact"),

    @Json(name = "user-fuzzy")
    userMinusFuzzy("user-fuzzy"),

    @Json(name = "account-exact")
    accountMinusExact("account-exact"),

    @Json(name = "account-fuzzy")
    accountMinusFuzzy("account-fuzzy"),

    @Json(name = "none")
    none("none");

}

