/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models


import com.squareup.moshi.Json

/**
* 
* Values: arts,music,moviesAmpersandTelevision,newspaperAmpersandMagazines,otherEntertainment,deposit,withdrawal,dividends,buy,sell,otherInvestments,gasAmpersandFuel,parking,maintenanceAmpersandRepairs,autoPayment,autoInsurance,publicTransportation,otherCar,airTravel,lodging,rideShareAmpersandRental,otherTravel,accountMaintenance,overdraftFee,insufficientFundsFee,aTMFee,checkOrderFee,interestChargedFee,foreignTransactionFee,wireFee,excessiveTransactionsFee,lateFee,cardMembershipFee,otherFee,rent,mortgage,otherHousing,rentReimbursement,creditCardPayment,aTMWithdrawals,internalTransfer,externalTransfer,otherTransfer,loanPayment,services,internet,phoneBill,utilities,tV,otherBills,paycheck,interest,reimbursement,otherIncome,tuition,studentLoan,otherEducation,healthInsurance,gym,dentist,doctor,pharmacy,otherHealthAmpersandFitness,groceries,coffee,restaurants,alcohol,otherFoodAmpersandDining,taxes,giftsAmpersandDonations,shopping,other
*/
enum class CleanCategory(val value: kotlin.String){

    @Json(name = "Arts")
    arts("Arts"),

    @Json(name = "Music")
    music("Music"),

    @Json(name = "Movies & Television")
    moviesAmpersandTelevision("Movies & Television"),

    @Json(name = "Newspaper & Magazines")
    newspaperAmpersandMagazines("Newspaper & Magazines"),

    @Json(name = "Other Entertainment")
    otherEntertainment("Other Entertainment"),

    @Json(name = "Deposit")
    deposit("Deposit"),

    @Json(name = "Withdrawal")
    withdrawal("Withdrawal"),

    @Json(name = "Dividends")
    dividends("Dividends"),

    @Json(name = "Buy")
    buy("Buy"),

    @Json(name = "Sell")
    sell("Sell"),

    @Json(name = "Other Investments")
    otherInvestments("Other Investments"),

    @Json(name = "Gas & Fuel")
    gasAmpersandFuel("Gas & Fuel"),

    @Json(name = "Parking")
    parking("Parking"),

    @Json(name = "Maintenance & Repairs")
    maintenanceAmpersandRepairs("Maintenance & Repairs"),

    @Json(name = "Auto Payment")
    autoPayment("Auto Payment"),

    @Json(name = "Auto Insurance")
    autoInsurance("Auto Insurance"),

    @Json(name = "Public Transportation")
    publicTransportation("Public Transportation"),

    @Json(name = "Other Car")
    otherCar("Other Car"),

    @Json(name = "Air Travel")
    airTravel("Air Travel"),

    @Json(name = "Lodging")
    lodging("Lodging"),

    @Json(name = "Ride Share & Rental")
    rideShareAmpersandRental("Ride Share & Rental"),

    @Json(name = "Other Travel")
    otherTravel("Other Travel"),

    @Json(name = "Account Maintenance")
    accountMaintenance("Account Maintenance"),

    @Json(name = "Overdraft Fee")
    overdraftFee("Overdraft Fee"),

    @Json(name = "Insufficient Funds Fee")
    insufficientFundsFee("Insufficient Funds Fee"),

    @Json(name = "ATM Fee")
    aTMFee("ATM Fee"),

    @Json(name = "Check Order Fee")
    checkOrderFee("Check Order Fee"),

    @Json(name = "Interest Charged Fee")
    interestChargedFee("Interest Charged Fee"),

    @Json(name = "Foreign Transaction Fee")
    foreignTransactionFee("Foreign Transaction Fee"),

    @Json(name = "Wire Fee")
    wireFee("Wire Fee"),

    @Json(name = "Excessive Transactions Fee")
    excessiveTransactionsFee("Excessive Transactions Fee"),

    @Json(name = "Late Fee")
    lateFee("Late Fee"),

    @Json(name = "Card Membership Fee")
    cardMembershipFee("Card Membership Fee"),

    @Json(name = "Other Fee")
    otherFee("Other Fee"),

    @Json(name = "Rent")
    rent("Rent"),

    @Json(name = "Mortgage")
    mortgage("Mortgage"),

    @Json(name = "Other Housing")
    otherHousing("Other Housing"),

    @Json(name = "Rent Reimbursement")
    rentReimbursement("Rent Reimbursement"),

    @Json(name = "Credit card payment")
    creditCardPayment("Credit card payment"),

    @Json(name = "ATM Withdrawals")
    aTMWithdrawals("ATM Withdrawals"),

    @Json(name = "Internal Transfer")
    internalTransfer("Internal Transfer"),

    @Json(name = "External Transfer")
    externalTransfer("External Transfer"),

    @Json(name = "Other Transfer")
    otherTransfer("Other Transfer"),

    @Json(name = "Loan Payment")
    loanPayment("Loan Payment"),

    @Json(name = "Services")
    services("Services"),

    @Json(name = "Internet")
    internet("Internet"),

    @Json(name = "Phone Bill")
    phoneBill("Phone Bill"),

    @Json(name = "Utilities")
    utilities("Utilities"),

    @Json(name = "TV")
    tV("TV"),

    @Json(name = "Other Bills")
    otherBills("Other Bills"),

    @Json(name = "Paycheck")
    paycheck("Paycheck"),

    @Json(name = "Interest")
    interest("Interest"),

    @Json(name = "Reimbursement")
    reimbursement("Reimbursement"),

    @Json(name = "Other Income")
    otherIncome("Other Income"),

    @Json(name = "Tuition")
    tuition("Tuition"),

    @Json(name = "Student Loan")
    studentLoan("Student Loan"),

    @Json(name = "Other Education")
    otherEducation("Other Education"),

    @Json(name = "Health Insurance")
    healthInsurance("Health Insurance"),

    @Json(name = "Gym")
    gym("Gym"),

    @Json(name = "Dentist")
    dentist("Dentist"),

    @Json(name = "Doctor")
    doctor("Doctor"),

    @Json(name = "Pharmacy")
    pharmacy("Pharmacy"),

    @Json(name = "Other Health & Fitness")
    otherHealthAmpersandFitness("Other Health & Fitness"),

    @Json(name = "Groceries")
    groceries("Groceries"),

    @Json(name = "Coffee")
    coffee("Coffee"),

    @Json(name = "Restaurants")
    restaurants("Restaurants"),

    @Json(name = "Alcohol")
    alcohol("Alcohol"),

    @Json(name = "Other Food & Dining")
    otherFoodAmpersandDining("Other Food & Dining"),

    @Json(name = "Taxes")
    taxes("Taxes"),

    @Json(name = "Gifts & Donations")
    giftsAmpersandDonations("Gifts & Donations"),

    @Json(name = "Shopping")
    shopping("Shopping"),

    @Json(name = "Other")
    other("Other");

}

