/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models

import dev.haven.client.models.ApiAccount

import com.squareup.moshi.Json
/**
 * 
 * @param accounts 
 */
data class GetAccountsResponse (
    @Json(name = "accounts")
    val accounts: kotlin.Array<ApiAccount>
) {

}

