/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param dark 
 * @param darker 
 * @param light 
 * @param primary 
 */
data class InstitutionColors (
    @Json(name = "dark")
    val dark: kotlin.String,
    @Json(name = "darker")
    val darker: kotlin.String,
    @Json(name = "light")
    val light: kotlin.String,
    @Json(name = "primary")
    val primary: kotlin.String
) {

}

