/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models

import dev.haven.client.models.Address
import dev.haven.client.models.CleanCategory
import dev.haven.client.models.OpenHours

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param address 
 * @param hours 
 * @param image 
 * @param category 
 * @param phone 
 * @param url 
 * @param facebook 
 * @param twitter 
 * @param instagram 
 * @param yelp 
 * @param updatedAt 
 */
data class Merchant (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "category")
    val category: CleanCategory,
    @Json(name = "updatedAt")
    val updatedAt: java.time.Instant,
    @Json(name = "address")
    val address: Address? = null,
    @Json(name = "hours")
    val hours: OpenHours? = null,
    @Json(name = "image")
    val image: kotlin.String? = null,
    @Json(name = "phone")
    val phone: kotlin.String? = null,
    @Json(name = "url")
    val url: kotlin.String? = null,
    @Json(name = "facebook")
    val facebook: kotlin.String? = null,
    @Json(name = "twitter")
    val twitter: kotlin.String? = null,
    @Json(name = "instagram")
    val instagram: kotlin.String? = null,
    @Json(name = "yelp")
    val yelp: kotlin.String? = null
) {

}

