/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models

import dev.haven.client.models.BadRequestServiceError
import dev.haven.client.models.ConflictServiceError
import dev.haven.client.models.NotFoundServiceError
import dev.haven.client.models.UnauthorizedServiceError
import dev.haven.client.models.UncaughtExceptionServiceError

import com.squareup.moshi.Json
/**
 * 
 * @param message 
 */
data class ServiceError (
    @Json(name = "message")
    val message: kotlin.String
) {

}

