/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models


import com.squareup.moshi.Json

/**
* 
* Values: aCH,fEE,dEBITCARD,cREDITCARD,rEVERSAL,cHARGEBACK,uNKNOWN
*/
enum class TransactionKind(val value: kotlin.String){

    @Json(name = "ACH")
    aCH("ACH"),

    @Json(name = "FEE")
    fEE("FEE"),

    @Json(name = "DEBIT_CARD")
    dEBITCARD("DEBIT_CARD"),

    @Json(name = "CREDIT_CARD")
    cREDITCARD("CREDIT_CARD"),

    @Json(name = "REVERSAL")
    rEVERSAL("REVERSAL"),

    @Json(name = "CHARGE_BACK")
    cHARGEBACK("CHARGE_BACK"),

    @Json(name = "UNKNOWN")
    uNKNOWN("UNKNOWN");

}

