/**
* Haven Money API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.haven.client.models


import com.squareup.moshi.Json

/**
* 
* Values: TRANSACTIONS,INSTITUTIONS
*/
enum class WebhookSubscription(val value: kotlin.String){

    @Json(name = "TRANSACTIONS")
    TRANSACTIONS("TRANSACTIONS"),

    @Json(name = "INSTITUTIONS")
    INSTITUTIONS("INSTITUTIONS");

}

