/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IHttpBody.h
 *
 * This is the interface for contents that can be sent to a remote HTTP server.
 */

#ifndef DEV_HAVEN_CLIENT_MODEL_IHttpBody_H_
#define DEV_HAVEN_CLIENT_MODEL_IHttpBody_H_


#include <iostream>

namespace dev {
namespace haven {
namespace client {
namespace model {

class  IHttpBody
{
public:
    virtual ~IHttpBody() { }

    virtual void writeTo( std::ostream& stream ) = 0;
};

}
}
}
}

#endif /* DEV_HAVEN_CLIENT_MODEL_IHttpBody_H_ */
