/*
 * Haven Money API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package haven
type BootstrapStrategy string

// List of BootstrapStrategy
const (
	USER_EXACT BootstrapStrategy = "user-exact"
	USER_FUZZY BootstrapStrategy = "user-fuzzy"
	ACCOUNT_EXACT BootstrapStrategy = "account-exact"
	ACCOUNT_FUZZY BootstrapStrategy = "account-fuzzy"
	NONE BootstrapStrategy = "none"
)