/*
 * Haven Money API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package haven

type Balance struct {
	Current string `json:"current"`
	Available *string `json:"available,omitempty"`
	Limit *string `json:"limit,omitempty"`
}
