/*
 * Haven Money API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package haven
type WebhookSubscription string

// List of WebhookSubscription
const (
	TRANSACTIONS WebhookSubscription = "TRANSACTIONS"
	INSTITUTIONS WebhookSubscription = "INSTITUTIONS"
)
