/*
 * Haven Money API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package haven
import (
	"time"
)

type Merchant struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Address *Address `json:"address,omitempty"`
	Hours *OpenHours `json:"hours,omitempty"`
	Image *string `json:"image,omitempty"`
	BackgroundImage *string `json:"backgroundImage,omitempty"`
	Category CleanCategory `json:"category"`
	Phone *string `json:"phone,omitempty"`
	Url *string `json:"url,omitempty"`
	Facebook *string `json:"facebook,omitempty"`
	Twitter *string `json:"twitter,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
	Yelp *string `json:"yelp,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}
