/*
 * Haven Money API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package haven
type TransactionKind string

// List of TransactionKind
const (
	ACH TransactionKind = "ACH"
	FEE TransactionKind = "FEE"
	DEBIT_CARD TransactionKind = "DEBIT_CARD"
	CREDIT_CARD TransactionKind = "CREDIT_CARD"
	REVERSAL TransactionKind = "REVERSAL"
	CHARGE_BACK TransactionKind = "CHARGE_BACK"
	UNKNOWN TransactionKind = "UNKNOWN"
)