/*
 * Haven Money API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package haven

type CreateWebhookRequest struct {
	Callback string `json:"callback"`
	Subscriptions []WebhookSubscription `json:"subscriptions"`
}
