/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountSubType } from './accountSubType';
import { AccountType } from './accountType';
import { Balance } from './balance';

export class AccountUpdate {
    'id': string;
    'user': string;
    'displayName': string;
    'displayNameDetailed': string;
    'institution': string;
    'institutionName': string;
    'accountType': AccountType;
    'accountSubType': AccountSubType;
    'balance': Balance;
    'createdAt': Date;
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "displayNameDetailed",
            "baseName": "displayNameDetailed",
            "type": "string"
        },
        {
            "name": "institution",
            "baseName": "institution",
            "type": "string"
        },
        {
            "name": "institutionName",
            "baseName": "institutionName",
            "type": "string"
        },
        {
            "name": "accountType",
            "baseName": "accountType",
            "type": "AccountType"
        },
        {
            "name": "accountSubType",
            "baseName": "accountSubType",
            "type": "AccountSubType"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "Balance"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return AccountUpdate.attributeTypeMap;
    }
}

