/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class InstitutionColors {
    'dark': string;
    'darker': string;
    'light': string;
    'primary': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dark",
            "baseName": "dark",
            "type": "string"
        },
        {
            "name": "darker",
            "baseName": "darker",
            "type": "string"
        },
        {
            "name": "light",
            "baseName": "light",
            "type": "string"
        },
        {
            "name": "primary",
            "baseName": "primary",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InstitutionColors.attributeTypeMap;
    }
}

