/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './address';
import { CleanCategory } from './cleanCategory';
import { OpenHours } from './openHours';

export class Merchant {
    'name': string;
    'address'?: Address;
    'hours'?: OpenHours;
    'image'?: string;
    'backgroundImage'?: string;
    'category': CleanCategory;
    'phone'?: string;
    'url'?: string;
    'facebook'?: string;
    'twitter'?: string;
    'instagram'?: string;
    'yelp'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Address"
        },
        {
            "name": "hours",
            "baseName": "hours",
            "type": "OpenHours"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "backgroundImage",
            "baseName": "backgroundImage",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "CleanCategory"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "facebook",
            "baseName": "facebook",
            "type": "string"
        },
        {
            "name": "twitter",
            "baseName": "twitter",
            "type": "string"
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "string"
        },
        {
            "name": "yelp",
            "baseName": "yelp",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Merchant.attributeTypeMap;
    }
}

