/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RawMerchant } from './rawMerchant';
import { RawMerchantStore } from './rawMerchantStore';
import { TransactionKind } from './transactionKind';
import { TransactionState } from './transactionState';

export class RawTransaction {
    'id': string;
    'account': string;
    'user': string;
    'rawMemo': string;
    'merchant'?: RawMerchant;
    'store'?: RawMerchantStore;
    'network'?: string;
    'userTransactedAt'?: Date;
    'amount': string;
    'categories': Array<string>;
    'kind': TransactionKind;
    'state': TransactionState;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "rawMemo",
            "baseName": "rawMemo",
            "type": "string"
        },
        {
            "name": "merchant",
            "baseName": "merchant",
            "type": "RawMerchant"
        },
        {
            "name": "store",
            "baseName": "store",
            "type": "RawMerchantStore"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "userTransactedAt",
            "baseName": "userTransactedAt",
            "type": "Date"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<string>"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "TransactionKind"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "TransactionState"
        }    ];

    static getAttributeTypeMap() {
        return RawTransaction.attributeTypeMap;
    }
}

