/**
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TenantServiceAccountAgentLoginResponse {
    'token': string;
    'expiry': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "expiry",
            "baseName": "expiry",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return TenantServiceAccountAgentLoginResponse.attributeTypeMap;
    }
}

