/*
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.haven.jclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WebhookSubscription
 */
@JsonAdapter(WebhookSubscription.Adapter.class)
public enum WebhookSubscription {
  
  TRANSACTIONS("TRANSACTIONS"),
  
  INSTITUTIONS("INSTITUTIONS");

  private String value;

  WebhookSubscription(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WebhookSubscription fromValue(String value) {
    for (WebhookSubscription b : WebhookSubscription.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WebhookSubscription> {
    @Override
    public void write(final JsonWriter jsonWriter, final WebhookSubscription enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WebhookSubscription read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WebhookSubscription.fromValue(value);
    }
  }
}

