/*
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BootstrapStrategy;
import org.openapitools.client.model.CleanCategory;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddAnnotationRequest
 */
public class AddAnnotationRequestTest {
    private final AddAnnotationRequest model = new AddAnnotationRequest();

    /**
     * Model tests for AddAnnotationRequest
     */
    @Test
    public void testAddAnnotationRequest() {
        // TODO: test AddAnnotationRequest
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'excludeFromBreakdowns'
     */
    @Test
    public void excludeFromBreakdownsTest() {
        // TODO: test excludeFromBreakdowns
    }

    /**
     * Test the property 'bootstrap'
     */
    @Test
    public void bootstrapTest() {
        // TODO: test bootstrap
    }

}
