/*
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.CleanCategory;
import org.openapitools.client.model.OpenHours;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Merchant
 */
public class MerchantTest {
    private final Merchant model = new Merchant();

    /**
     * Model tests for Merchant
     */
    @Test
    public void testMerchant() {
        // TODO: test Merchant
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'backgroundImage'
     */
    @Test
    public void backgroundImageTest() {
        // TODO: test backgroundImage
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'facebook'
     */
    @Test
    public void facebookTest() {
        // TODO: test facebook
    }

    /**
     * Test the property 'twitter'
     */
    @Test
    public void twitterTest() {
        // TODO: test twitter
    }

    /**
     * Test the property 'instagram'
     */
    @Test
    public void instagramTest() {
        // TODO: test instagram
    }

    /**
     * Test the property 'yelp'
     */
    @Test
    public void yelpTest() {
        // TODO: test yelp
    }

}
