/*
 * Haven Money API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BadRequestServiceError;
import org.openapitools.client.model.ConflictServiceError;
import org.openapitools.client.model.NotFoundServiceError;
import org.openapitools.client.model.TooManyRequestsServiceError;
import org.openapitools.client.model.UnauthorizedServiceError;
import org.openapitools.client.model.UncaughtExceptionServiceError;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServiceError
 */
public class ServiceErrorTest {
    private final ServiceError model = new ServiceError();

    /**
     * Model tests for ServiceError
     */
    @Test
    public void testServiceError() {
        // TODO: test ServiceError
    }

}
